# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    # timeout: 15

    # caching settings
    # can greatly improve speed
    # off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}
      local_group_id: "SELECT id, name FROM local_groups ORDER BY LOWER(name) ASC"
      working_group_id: "SELECT id, name FROM working_groups ORDER BY LOWER(name) ASC"
      rebel_availability: { 'unavailable': 'Unavailable', 'few_hours_a_month': 'A few hours a month', 'few_hours_a_week': 'A couple of hours a week', '10_hours_a_week': 'More than 10 hours a week' }
      skill_id: "SELECT id, name FROM skills ORDER BY LOWER(name) ASC"
      tag_id: "SELECT id, tag FROM tags ORDER BY LOWER(name) ASC"

    linked_columns:
      # user_id: "/admin/users/{value}"
      local_group_id: "/local_groups/{value}"
      rebel_id: "/rebels/{value}"
      skill_id: "/skills/{value}"
      user_id: "/users/{value}"
      working_group_id: "/working_groups/{value}"

    smart_columns:
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"
      local_group_id: "SELECT id, name FROM local_groups WHERE id IN {value}"
      rebel_id: "SELECT id, name FROM rebels WHERE id IN {value}"
      skill_id: "SELECT id, name FROM skills WHERE id IN {value}"
      tag_id: "SELECT id, name FROM tags WHERE id IN {value}"
      working_group_id: "SELECT id, name FROM working_groups WHERE id IN {value}"

# create audits
audit: true

# change the time zone
time_zone: "Brussels"

# class name of the user model
# user_class: User

# method name for the current user
# user_method: current_user

# method name for the display name
# user_name: name

# custom before_action to use for auth
# before_action_method: require_admin

# email to send checks from
# from_email: blazer@example.org

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: trend / r

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: trend

# enable map
# mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>
